# FINAL EXAM (2023) - Questions to study (ie. everything)

# Sections on this page (click to get to the section you want)

<ul>

<li><a href="#yr-aboutTheseQuestions" />ABOUT THESE QUESTIONS</a>
</li>

<li><a href="#yr-final-questions" />Study material for FINAL (also see midterm study material)</a>
</li>

<li><a href="#yr-midterm-questions" />Study material for MIDTERM (for your reference)</a>
</li>

</ul>

---

<span id="yr-aboutTheseQuestions" />

## About these questions/answers

***The answers to each question were written to explain how to think about arriving at the answer.***

***The actual answer is on the line containing the comment #ANSWER. All other lines are there to demonstrate the answer working on actual data or to demonstrate portions of the whole answer so that the whole answer is more easily understood. If the actual required code for an answer takes up several lines then the comment will say #ANSWER (MULTIPLE LINES).***

***If different possible answers are shown, then the different answers will be displayed with the comment #ALTERNATE ANSWER or #ANOTHER ANSWER.***\
***Note that it is very possible that there are valid answers other than the ones shown below.***

---


<span id="yr-final-questions" />

## Final Exam

The final is cumulative in that
you **MUST KNOW the material from before the midterm** in order to 
be able to answer questions that cover material from after the midterm.
See <a href="#yr-midterm-questions">below</a> for the list of questions 
from the midterm material.

With that said, ALL of the questions on this website 
are good study material for the final. 

For your convenience I listed below those questions on this website
that were not listed in the study material for the 
<a href="#yr-midterm-questions">midterm</a>.

There are plenty of practice questions here but I will try to continue to 
post additional practice questions.

### FINAL Practice Questions - TOPIC: Vectors 1

*All of this material was already on the midterm.*


### FINAL Practice Questions - TOPIC Vectors2

*(See <a href="#yr-midterm-questions">below</a> for which questions were in the midterm study material.)*

The following questions were ***NOT*** listed in midterm study material:

Questions: 12, 13 (Topic: named vectors)

Questions: 24 (Topic: parallel vectors - wasn't included for midterm - should have been)

Questions: 32

Questions: 45 - end

### FINAL Practice Questions - TOPIC: User Defined Functions

*(The midterm material only included four of these questions - see <a href="#yr-midterm-questions">below</a>.)*

***ALL of this material is relevant for the final exam.***  

In addition to basic idea of user defined functions, these questions also cover  
if, while loop, for loop (we will cover the for loop soon)  

### FINAL Practice Questions - TOPIC: Dataframes

*None of this material was on the midterm.*

***ALL of this material is relevant for the final exam.***  

In addition to basic data.frame concepts these questions also 
cover &, |, sample, lapply

### FINAL Practice Questions - TOPIC: Assorted Topics

*(See <a href="#yr-midterm-questions">below</a> for which questions were in the midterm study material.)*

*The following questions were not in midterm study material:  *

Questions: 74 (topic: dataframes)  

Questions: 80 (topics: lists, loops)  


### FINAL Practice Questions - TOPIC: Parallel Vectors, other assorted questions

*(See <a href="#yr-midterm-questions">below</a> for which questions were in the midterm study material.)*

*The following questions were not in midterm study material:*

Questions: 3  (&, |)

Questions: 7,8,9,10,11,12,13,14,15,16,17,18  (&, |)

Questions: 39, 40   (topics: scientific notation)



---

***BELOW ARE THE QUESTIONS THAT WERE FROM THE MATERIAL BEFORE THE MIDTERM.***
***IF YOU AREN'T YET COMFORTABLE WITH THIS MATERIAL YET YOU SHOULD ALSO***
***STUDY THESE AS THE LATER MATERIAL DEPENDS ON THIS EARLIER MATERIAL.***

---

<span id="yr-midterm-questions" />

# Midterm Exam 

**The following questions are related to the material for the midterm.**

### Practice Questions - TOPIC Vectors1

1-17 (all questions)

### Practice Questions - TOPIC Vectors2

1,2,3,4,5,6,\
8,9,10,11,\
14,15,16,17,18,19,20,21,22,23,\
25,26,27,28,29,30,31,\
33,34,35,36,37,38,39,40,41,42

### Practice Questions - TOPIC: User Defined Functions

67, 68,\
71a, 71b

### Practice Questions - TOPIC: Dataframes

none

### Practice Questions - TOPIC: Assorted Topics

73,\
75, 76, 77, 78, 79,\
81

### Practice Questions - TOPIC: Parallel Vectors, other assorted questions

1,2,\
4,5,6,\
19,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38

