# About This Website {.unnumbered}

This website is for the use of my students at YU.

The menu on the left lists the "chapters" in the "book". When you click on a "chapter" from the left hand menu, you should see another menu appear on the right hand side of the screen. The menu on the right side contains links to sections in that chapter. It's not perfect, but I'm working on improving the links.

One of the many nice things about this website is that the output of all R code is shown below the actual R code (see the website to see what I mean). The output is actually generated by R. Therefore, if there is a difference between my comments and the output shown below the code, then I must have made a typo in my comments. You can trust the results displayed below the code more than the #comments that I wrote.

FYI - I created this website by using "Quarto" which is the new version of what has for years been called "R Markdown". Quarto simplifies the publishing this type of content online, or in a PDF, or an ebook, etc.

-Prof. Rosenthal

<!--- COMMENTED OUT 
# Updates to this website

I'll be updating this and improving it on a regular basis. If you are interested. I will list the updates below.

-Prof. Rosenthal

Added suggested answers to the Vectors1 practice problems.

+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11/05/2023  | Added suggested answers to the Vectors1 practice problems.                                                                                                                                 |
|             |                                                                                                                                                                                            |
|             | Added missing entry "Logical vectors, relational (AKA logical) operators, ifelse" We covered this in class and it was on Canvas but it had been inadvertantly not included on the website. |
|             |                                                                                                                                                                                            |
|             | Fixed a few typos.                                                                                                                                                                         |
|             |                                                                                                                                                                                            |
|             | Fixed PDF file.                                                                                                                                                                            |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10/31/2023  | Added more chapters to the website.                                                                                                                                                        |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10/26/2023  | Original website.                                                                                                                                                                          |
+-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

END COMMENTED OUT --->