name: Deploy to rnotesWebsite

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rnotes repo
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to rnotesWebsite
        run: |
          git remote add rnotesWebsite git@github.com:y-rosenthal/rnotesWebsite.git
          git push rnotesWebsite master
